/** @type {import('jest').Config} */
module.exports = {
  preset: 'jest-expo',
  testMatch: ['**/__tests__/**/*.[jt]s?(x)', '**/*.test.[jt]s?(x)'],
  testPathIgnorePatterns: ['/node_modules/', '/tests/index.tsx', 'StyledText-test\\.js'],
  setupFilesAfterEnv: ['<rootDir>/test/setup/jest-setup.ts'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
  },
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|@gluestack-ui/.*|@legendapp/.*|moti)',
  ],
  collectCoverageFrom: [
    'services/**/*.ts',
    'hooks/**/*.ts',
    'hooks/**/*.tsx',
    'stores/**/*.ts',
    'lib/**/*.ts',
    'lib/**/*.tsx',
    'components/**/*.ts',
    'components/**/*.tsx',
    'app/**/*.ts',
    'app/**/*.tsx',
    '!components/ui/**',
    '!**/__tests__/**',
    '!**/node_modules/**',
    '!**/index.ts',
    '!**/*.d.ts',
  ],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '\\.expo/',
    'expo-env\\.d\\.ts',
    '\\+html\\.tsx',
    '\\+not-found\\.tsx',
    'components/ui/',
  ],
  coverageThreshold: {
    global: {
      branches: 40,
      functions: 50,
      lines: 50,
      statements: 50,
    },
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  testTimeout: 10000,
  clearMocks: true,
  resetMocks: true,
};
