http:
  routers:
    portfolio:
      rule: "Host(`nicebyte.ia.br`) || Host(`www.nicebyte.ia.br`)"
      entryPoints:
        - websecure
      tls: {}
      service: portfolio-svc
      middlewares:
        - crowdsec-bouncer@file
        - cloudflare-only@file
        - security-headers@file

  services:
    portfolio-svc:
      loadBalancer:
        servers:
          - url: "http://proxy-portfolio-1:3000"
