tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/origin.crt
        keyFile: /etc/traefik/certs/origin.key

  certificates:
    - certFile: /etc/traefik/certs/origin.crt
      keyFile: /etc/traefik/certs/origin.key
